// AUTO-GENERATED tool-translation dictionary (ru -> uz). Merged from _deploy_tmp/uztrans/batch_*.json.
// Do not hand-edit large blocks; regenerate via _deploy_tmp/_merge_uz.cjs. Manual patch entries may be appended at the end.
export const TOOLS_UZ = {
  "— Выбрать —": "— Tanlash —",
  "— не указана —": "— ko'rsatilmagan —",
  "— не указано —": "— ko'rsatilmagan —",
  "«5 идей зимних подарков» или «Распаковка нового товара»": "«Qishki sovg'alar uchun 5 ta g'oya» yoki «Yangi tovarni ochish»",
  "«А вы знали что 80% покупателей выбирают глазами?»": "«80% xaridorlar ko'zi bilan tanlashini bilarmidingiz?»",
  "«Боится переплатить · нет времени на сравнение»": "«Ortiqcha to'lashdan qo'rqadi · solishtirishga vaqti yo'q»",
  "«Дорого · долго ждать доставку · не уверен в качестве»": "«Qimmat · yetkazib berishni uzoq kutish · sifatga ishonchsiz»",
  "«Дорого»": "«Qimmat»",
  "«Здравствуйте, я знаю что ваш бизнес работает с деревом. У меня 30 секунд?»": "«Assalomu alaykum, bilaman, sizning biznesingiz yog'och bilan ishlaydi. Menda 30 soniya bormi?»",
  "«Многие наши клиенты теряли деньги на нестабильных поставщиках...»": "«Ko'p mijozlarimiz beqaror yetkazib beruvchilarda pul yo'qotgan...»",
  "«Можем встретиться завтра в 11 или после обеда — что удобнее?»": "«Ertaga soat 11 da yoki tushdan keyin uchrashishimiz mumkin — qaysi biri qulay?»",
  "«Мы делаем так, что [результат за число]»": "«Biz shuni qilamizki, [sanada natija]»",
  "«Не сейчас»": "«Hozir emas»",
  "«Нет бюджета»": "«Byudjet yo'q»",
  "«Пиши «хочу» в комменты» / «Заходи на сайт»": "«Izohlarga «xohlayman» deb yoz» / «Saytga kir»",
  "«Подумаю»": "«O'ylab ko'raman»",
  "«Почему продажи упали в мае?», «Что плохо продаётся?»...": "«Nega may oyida sotuvlar tushdi?», «Nima yomon sotilyapti?»...",
  "«Сейчас не до этого»": "«Hozir bunga vaqt yo'q»",
  "«У конкурентов дешевле»": "«Raqobatchilarda arzonroq»",
  "«Хук про экономию зашёл — досмотры 80%. CTA слабый, мало комментов. В следующий раз вопрос в конце.»": "«Tejamkorlik haqidagi hook ishladi — oxirigacha ko'rish 80%. CTA zaif, izohlar kam. Keyingi safar oxirida savol.»",
  "«Чтобы быстро купить подарок ребёнку, не выходя из дома»": "«Uydan chiqmasdan bolaga tez sovg'a sotib olish uchun»",
  "← Назад": "← Orqaga",
  "↓ Расход": "↓ Chiqim",
  "+ Атрибут": "+ Atribut",
  "+ Добавить": "+ Qo'shish",
  "+ Добавить портрет": "+ Portret qo'shish",
  "+ Заказ": "+ Buyurtma",
  "+ закрытые распродажи": "+ yopiq chegirmalar",
  "+ Кампания": "+ Kampaniya",
  "+ Курс": "+ Kurs",
  "+ Новый товар": "+ Yangi tovar",
  "+ Опрос": "+ So'rov",
  "+ персональный менеджер": "+ shaxsiy menejer",
  "+ поздравления с ДР": "+ tug'ilgan kun bilan tabriklar",
  "+ Приход": "+ Kirim",
  "+ Создать первый портрет": "+ Birinchi portretni yaratish",
  "+ Сценарий": "+ Stsenariy",
  "+ Тип": "+ Tur",
  "+340K вернуть": "+340K qaytarish",
  "+4.2M / мес": "+4.2M / oy",
  "+40% выручка": "+40% tushum",
  "+8.5M cash": "+8.5M cash",
  "< 10% — поднять цену": "< 10% — narxni ko'tarish",
  "< 30 дн": "< 30 kun",
  "= Валовая прибыль": "= Yalpi foyda",
  "= ЧИСТАЯ ПРИБЫЛЬ": "= SOF FOYDA",
  "= EBITDA": "= EBITDA",
  "> 7 дней": "> 7 kun",
  "> 7 дней или без срока": "> 7 kun yoki muddatsiz",
  "− Аренда": "− Ijara",
  "− Зарплаты": "− Ish haqi",
  "− Маркетинг": "− Marketing",
  "− Налоги": "− Soliqlar",
  "− Прочее": "− Boshqa",
  "− Себестоимость": "− Tannarx",
  "−8.5M риск": "−8.5M xavf",
  "≈ В рынке": "≈ Bozorda",
  "≤ 7 дней": "≤ 7 kun",
  "⏳ В работе": "⏳ Ishda",
  "⏳ Ждёт": "⏳ Kutmoqda",
  "⏸ Пауза": "⏸ Pauza",
  "▶️ Открыть": "▶️ Ochish",
  "● Активна": "● Faol",
  "⚙️ Атрибуты": "⚙️ Atributlar",
  "⚙️ Атрибуты товаров": "⚙️ Tovarlar atributlari",
  "⚠️ Дороже": "⚠️ Qimmatroq",
  "⚠️ Контроль рисков": "⚠️ Risklarni nazorat",
  "⚠️ Мало": "⚠️ Kam",
  "⚡ 1:1 с Anvar S.": "⚡ Anvar S. bilan 1:1",
  "⚡ Автоматизация": "⚡ Avtomatlashtirish",
  "✅ Активные": "✅ Faol",
  "✅ Опублик.": "✅ Chop etilgan",
  "✅ Опубликовано": "✅ Chop etilgan",
  "✉️ Ответить на email-ы (47)": "✉️ Email-larga javob berish (47)",
  "✓ Доставлен": "✓ Yetkazildi",
  "✓ Доставлено": "✓ Yetkazildi",
  "✓ Лучшая цена": "✓ Eng yaxshi narx",
  "✓ Нет алертов в этой категории — отличная работа!": "✓ Bu toifada ogohlantirishlar yo'q — ajoyib ish!",
  "✓ Подтверждено": "✓ Tasdiqlandi",
  "✓ Приход": "✓ Kirim",
  "✓ Работает на сервере": "✓ Serverda ishlamoqda",
  "✨ Новые": "✨ Yangi",
  "⭐ NPS / Опросы": "⭐ NPS / So'rovlar",
  "🌍 Масштабирование": "🌍 Masshtablash",
  "🌐 Портал": "🌐 Portal",
  "🍽️ Корп. обед": "🍽️ Korporativ tushlik",
  "🎁 Наборы": "🎁 To'plamlar",
  "🎁 Программа лояльности": "🎁 Sodiqlik dasturi",
  "🎓 Управление": "🎓 Boshqaruv",
  "🎣 Hook (первые 3 секунды)": "🎣 Hook (birinchi 3 soniya)",
  "🎬 Конструктор контента": "🎬 Kontent konstruktori",
  "🎬 Обучение": "🎬 O'qitish",
  "🎯 Анализ ЦА (JTBD · портреты · боли)": "🎯 Auditoriya tahlili (JTBD · portretlar · og'riqlar)",
  "🎯 Планирование": "🎯 Rejalashtirish",
  "🎯 Сегментация клиентов": "🎯 Mijozlar segmentatsiyasi",
  "🎯 Стадия воронки": "🎯 Voronka bosqichi",
  "🎯 Стратегия на 2027": "🎯 2027 uchun strategiya",
  "🎯 CTA (что сделать читателю)": "🎯 CTA (o'quvchi nima qilishi kerak)",
  "🎰 Применить →": "🎰 Qo'llash →",
  "🎰 Что-если симулятор": "🎰 Nima-bo'lsa simulyatori",
  "🏆 Мотивация": "🏆 Motivatsiya",
  "🏛 Перечисление": "🏛 Pul o'tkazish",
  "🏢 Бренды": "🏢 Brendlar",
  "🏢 B2B": "🏢 B2B",
  "🏢 B2B / B2G сделки": "🏢 B2B / B2G bitimlar",
  "🏦 Касса": "🏦 Kassa",
  "🏦 Кассы": "🏦 Kassalar",
  "🏦 Перевод": "🏦 O'tkazma",
  "🏭 Поставщики": "🏭 Yetkazib beruvchilar",
  "🏷️ Справочники": "🏷️ Ma'lumotnomalar",
  "🏷️ Типы": "🏷️ Turlar",
  "🏷️ Типы товаров": "🏷️ Tovar turlari",
  "🏷️ Ценообразование": "🏷️ Narx belgilash",
  "👋 Ушли": "👋 Ketgan",
  "👑 VIP": "👑 VIP",
  "👤 Картотека HR": "👤 HR kartotekasi",
  "👥 Клиентская база": "👥 Mijozlar bazasi",
  "👥 Найм 2 менеджеров B2B": "👥 2 ta B2B menejer yollash",
  "👥 KPI команды": "👥 Jamoa KPI",
  "💎 LTV клиентов": "💎 Mijozlar LTV",
  "💳 Карта": "💳 Karta",
  "💵 Нал": "💵 Naqd",
  "💵 Наличные": "💵 Naqd pul",
  "💾 Принять": "💾 Qabul qilish",
  "💾 Сохранить": "💾 Saqlash",
  "📅 Запланировано": "📅 Rejalashtirilgan",
  "📅 Май 2026 ▾": "📅 May 2026 ▾",
  "📈 Финансовая модель": "📈 Moliyaviy model",
  "📊 Отчёт сейчас": "📊 Hozir hisobot",
  "📊 ABC / XYZ анализ": "📊 ABC / XYZ tahlil",
  "📊 P&L отчёт": "📊 P&L hisobot",
  "📋 В долг": "📋 Qarzga",
  "📋 Закупки": "📋 Xaridlar",
  "📋 История продаж": "📋 Sotuvlar tarixi",
  "📌 Другое": "📌 Boshqa",
  "📍 Точки контакта": "📍 Kontakt nuqtalari",
  "📐 Единицы": "📐 Birliklar",
  "📐 Единицы измерения": "📐 O'lchov birliklari",
  "📑 Перечисл.": "📑 O'tkazma",
  "📑 Перечисление": "📑 Pul o'tkazish",
  "📒 Долги клиентов": "📒 Mijozlar qarzlari",
  "📒 Долги поставщикам": "📒 Yetkazib beruvchilarga qarzlar",
  "📖 Основной текст / структура": "📖 Asosiy matn / tuzilma",
  "📚 Запустить онлайн-обучение": "📚 Onlayn o'qitishni ishga tushirish",
  "📞 Перезвонить поставщику X": "📞 X yetkazib beruvchiga qayta qo'ng'iroq qilish",
  "📞 Скрипты продаж": "📞 Sotuv skriptlari",
  "📡 Каналы и ROI": "📡 Kanallar va ROI",
  "📡 Лидогенерация": "📡 Lidlar generatsiyasi",
  "📣 Кампании": "📣 Kampaniyalar",
  "📣 Реклама": "📣 Reklama",
  "📥 Импорт": "📥 Import",
  "📥 Приход товара": "📥 Tovar kirimi",
  "📦 Забран": "📦 Olingan",
  "📦 Остатки склада": "📦 Ombor qoldiqlari",
  "📦 Товары": "📦 Tovarlar",
  "📦 Товары и остатки": "📦 Tovarlar va qoldiqlar",
  "📺 Просмотр трендов": "📺 Trendlarni ko'rish",
  "🔌 Интеграции": "🔌 Integratsiyalar",
  "🔍 Инвентаризация": "🔍 Inventarizatsiya",
  "🔍 Найти чат": "🔍 Chatni topish",
  "🔍 Поиск по имени или телефону...": "🔍 Ism yoki telefon bo'yicha qidiruv...",
  "🔍 Поиск по названию или штрих-коду...": "🔍 Nomi yoki shtrix-kod bo'yicha qidiruv...",
  "🔍 Разбор: что залетело / что нет / почему": "🔍 Tahlil: nima muvaffaqiyatli / nima yo'q / nega",
  "🔍 Товар, клиент или № продажи…": "🔍 Tovar, mijoz yoki sotuv №…",
  "🔐 Безопасность": "🔐 Xavfsizlik",
  "🔗 Подключить": "🔗 Ulash",
  "🔗 Референс / ссылка на пост": "🔗 Referens / postga havola",
  "🔥 Решить долг TashTrade": "🔥 TashTrade qarzini hal qilish",
  "🔭 Конкуренты": "🔭 Raqobatchilar",
  "🔴 Критично": "🔴 Kritik",
  "🔴 Низкая маржа": "🔴 Past marja",
  "🔴 Просрочены": "🔴 Muddati o'tgan",
  "🔵 Инфо": "🔵 Ma'lumot",
  "🗑️ Списать": "🗑️ Hisobdan chiqarish",
  "🗓️ Стратегия 3 года": "🗓️ 3 yillik strategiya",
  "🤖 Авто-слияние": "🤖 Avto-birlashtirish",
  "🤖 AI-консультант": "🤖 AI-maslahatchi",
  "🤝 Сарафан": "🤝 Og'izaki",
  "🧑‍💼 Сотрудники компании": "🧑‍💼 Kompaniya xodimlari",
  "😴 Спящие": "😴 Uxlayotgan",
  "🚀 Начать сверку": "🚀 Solishtirishni boshlash",
  "🚚 В пути": "🚚 Yo'lda",
  "🚚 Логистика": "🚚 Logistika",
  "🚨 Закрыть кассовый разрыв": "🚨 Kassa uzilishini yopish",
  "🚫 Нет в наличии": "🚫 Mavjud emas",
  "🚫 Отменено": "🚫 Bekor qilingan",
  "🚶 Прохожий": "🚶 O'tkinchi",
  "🛍 Розница": "🛍 Chakana",
  "🛑 Завершить": "🛑 Yakunlash",
  "🛒 Касса · монитор смены": "🛒 Kassa · smena monitori",
  "🛒 Маркетплейс": "🛒 Marketpleys",
  "🛡️ Контроль данных": "🛡️ Ma'lumotlar nazorati",
  "🟡 Внимание": "🟡 Diqqat",
  "🟡 Скоро срок": "🟡 Muddati yaqin",
  "🟡 Средняя": "🟡 O'rtacha",
  "🟢 В сроке": "🟢 Muddatida",
  "🟢 Здоровая": "🟢 Sog'lom",
  "0-2 покупки": "0-2 xarid",
  "120+ дн": "120+ kun",
  "14 излишков + 10 недостач": "14 ortiqcha + 10 kamomad",
  "14 февраля + 8 марта": "14 fevral + 8 mart",
  "15% выручки": "tushumning 15%",
  "1М-3М/мес": "1M-3M/oy",
  "1С Бухгалтерия": "1S Buxgalteriya",
  "2 184 активных · история · сегменты": "2 184 faol · tarix · segmentlar",
  "200К-500К/мес": "200K-500K/oy",
  "3-9 покупок": "3-9 xarid",
  "3М+/мес": "3M+/oy",
  "5% выручки": "tushumning 5%",
  "500К-1М/мес": "500K-1M/oy",
  "60-120 дн": "60-120 kun",
  "70% конкурентов отказывают": "raqobatchilarning 70% rad etadi",
  "8 марта пик · Навруз": "8 mart cho'qqi · Navro'z",
  "80% выручки": "tushumning 80%",
  "9/10 — «Доставка быстрая, ассортимент богатый»": "9/10 — «Yetkazish tez, assortiment boy»",
  "А когда планируете? Зафиксирую цену для вас на 30 дней.": "Qachon rejalashtiryapsiz? Siz uchun narxni 30 kunga belgilab qo'yaman.",
  "А с чем сравниваете? Покажу выгоду в долгосрочной перспективе.": "Nima bilan solishtiryapsiz? Uzoq muddatli foydani ko'rsataman.",
  "Август": "Avgust",
  "Авто-разнесение выписки": "Ko'chirmani avto-taqsimlash",
  "Агрессивное повышение": "Agressiv oshirish",
  "админ": "admin",
  "Админ": "Admin",
  "Адрес": "Manzil",
  "Аккуратное повышение": "Ehtiyotkor oshirish",
  "активен": "faol",
  "Активен": "Faol",
  "Активна": "Faol",
  "Активно": "Faol",
  "Активность": "Faollik",
  "Активные": "Faol",
  "Активные акции · промо · обзвон": "Faol aksiyalar · promo · qo'ng'iroqlar",
  "Активные доставки": "Faol yetkazishlar",
  "активных": "faol",
  "Активных": "Faol",
  "алертов": "ogohlantirish",
  "Алерты": "Ogohlantirishlar",
  "Анализирую данные за месяц... Готов отвечать на конкретные вопросы о бизнесе.": "Oylik ma'lumotlarni tahlil qilyapman... Biznes haqidagi aniq savollarga javob berishga tayyorman.",
  "Анализирую... Это сложный вопрос — обратитесь к подробным отчётам или уточните формулировку.": "Tahlil qilyapman... Bu murakkab savol — batafsil hisobotlarga murojaat qiling yoki savolni aniqlashtiring.",
  "Аналитика": "Analitika",
  "Апр": "Apr",
  "Апрель": "Aprel",
  "Аренда": "Ijara",
  "Атрибутов": "Atributlar",
  "Атрибуты": "Atributlar",
  "База поставщиков · контакты · история": "Yetkazib beruvchilar bazasi · kontaktlar · tarix",
  "Базовые цены": "Bazaviy narxlar",
  "Базовый кэшбек": "Asosiy keshbek",
  "Баланс": "Balans",
  "баланс кассы к концу недели составит": "hafta oxiriga kassa balansi quyidagicha bo'ladi",
  "Банк-клиент": "Bank-mijoz",
  "Без бренда": "Brendsiz",
  "Без ед.": "Birliksiz",
  "Без клиента": "Mijozsiz",
  "Без покупок 120+ дней или никогда не покупали": "120+ kun xaridsiz yoki hech qachon xarid qilmagan",
  "Без покупок 60-120 дней — реактивация": "60-120 kun xaridsiz — reaktivatsiya",
  "Без поставщика": "Yetkazib beruvchisiz",
  "Безопасно": "Xavfsiz",
  "Бейсболка синяя": "Ko'k beysbolka",
  "Бейсболка синяя × 2, Шахматы × 1 · 580K UZS": "Ko'k beysbolka × 2, Shaxmat × 1 · 580K UZS",
  "бизнес-консультант · ответы кратко по делу": "biznes-maslahatchi · javoblar qisqa va aniq",
  "Бизнес-процессов": "Biznes-jarayonlar",
  "Битые": "Buzilgan",
  "Боли": "Og'riqlar",
  "Боли / страхи": "Og'riqlar / qo'rquvlar",
  "Боль": "Og'riq",
  "Бренд": "Brend",
  "Бренд создан": "Brend yaratildi",
  "Бренды": "Brendlar",
  "Брус 50×100": "Brus 50×100",
  "было": "edi",
  "Быстрые сценарии": "Tezkor stsenariylar",
  "Бюджет": "Byudjet",
  "Бюджет на месяц": "Oylik byudjet",
  "Бюджет на покупки": "Xaridlar uchun byudjet",
  "В договоре": "Shartnomada",
  "В долг": "Qarzga",
  "В доставке": "Yetkazishda",
  "в каталоге": "katalogda",
  "В команде": "Jamoada",
  "в компании": "kompaniyada",
  "в месяц": "oyiga",
  "В наличии": "Mavjud",
  "в норме": "me'yorda",
  "в плане": "rejada",
  "В плане": "Rejada",
  "В процессе": "Jarayonda",
  "В разработке": "Ishlab chiqilmoqda",
  "В сделку": "Bitimga",
  "в системе с": "tizimda",
  "в среднем": "o'rtacha",
  "В сроке": "Muddatida",
  "В Telegram откройте @BotFather → /newbot → скопируйте токен": "Telegramda @BotFather oching → /newbot → tokenni nusxalang",
  "валовая": "yalpi",
  "Валовая": "Yalpi",
  "Валовая прибыль": "Yalpi foyda",
  "Валют в обороте": "Aylanmadagi valyutalar",
  "Валюты в обороте (из ваших операций)": "Aylanmadagi valyutalar (sizning operatsiyalaringizdan)",
  "ваш аккаунт": "sizning akkauntingiz",
  "Введите название": "Nomini kiriting",
  "Введите сумму": "Summani kiriting",
  "Вес": "Og'irlik",
  "вес г": "og'irlik g",
  "Весна 2026 — скидки": "Bahor 2026 — chegirmalar",
  "Видео": "Video",
  "Видео обзор": "Video sharh",
  "Видео-урок in-app": "Ilova ichidagi video-dars",
  "Видит пост": "Postni ko'radi",
  "Витрина": "Vitrina",
  "включён": "yoqilgan",
  "влажность %": "namlik %",
  "Внимание": "Diqqat",
  "Во время покупки": "Xarid vaqtida",
  "вовлечение": "jalb etish",
  "Возврат 100%": "100% qaytarish",
  "Возврат 100% без вопросов": "Savolsiz 100% qaytarish",
  "Возражения": "E'tirozlar",
  "Возраст": "Yosh",
  "Воронка": "Voronka",
  "Воронка TOFU/MOFU/BOFU · план/факт · анализ после публикации": "Voronka TOFU/MOFU/BOFU · reja/fakt · chop etishdan keyin tahlil",
  "Все": "Hammasi",
  "Всё": "Hammasi",
  "Всё в сроке": "Hammasi muddatida",
  "Все оплаты": "Barcha to'lovlar",
  "Все продажи компании · реальные данные": "Kompaniyaning barcha sotuvlari · haqiqiy ma'lumotlar",
  "Все сотрудники": "Barcha xodimlar",
  "Всё спокойно": "Hammasi tinch",
  "Все типы": "Barcha turlar",
  "все филиалы": "barcha filiallar",
  "Всего": "Jami",
  "Всего брендов": "Jami brendlar",
  "Всего в команде": "Jamoada jami",
  "Всего долгов": "Jami qarzlar",
  "Всего единиц": "Jami birliklar",
  "всего клиентов": "jami mijozlar",
  "Всего на рекламу": "Reklamaga jami",
  "Всего портретов": "Jami portretlar",
  "Всего публикаций": "Jami nashrlar",
  "Всего типов": "Jami turlar",
  "Всего товаров": "Jami tovarlar",
  "Вставьте токен ниже и нажмите «Найти чат»": "Tokenni quyiga joylang va «Chatni topish» bosing",
  "вчера": "kecha",
  "Вы прошли точку безубыточности — бизнес в плюсе": "Siz zararsizlik nuqtasidan o'tdingiz — biznes plyusda",
  "Выберите чат для уведомлений:": "Bildirishnomalar uchun chatni tanlang:",
  "Выбор": "Tanlash",
  "выбранный филиал": "tanlangan filial",
  "Выбрано": "Tanlandi",
  "Выгрузка бухгалтеру": "Buxgalterga yuklash",
  "Выгрузка в формате 1С. Подключим по запросу.": "1S formatida yuklash. So'rov bo'yicha ulaymiz.",
  "Выиграно": "Yutildi",
  "Выплачено бонусов": "To'langan bonuslar",
  "Выполнено": "Bajarildi",
  "Выпускников": "Bitiruvchilar",
  "вырастет": "oshadi",
  "Выручка": "Tushum",
  "Выручка · себестоимость · маржа · прибыль": "Tushum · tannarx · marja · foyda",
  "Выручка (месяц)": "Tushum (oy)",
  "Выручка (посл. месяц)": "Tushum (oxirgi oy)",
  "выручка / мес": "tushum / oy",
  "Выручка / мес (факт)": "Tushum / oy (fakt)",
  "Выручка → себестоимость → расходы → чистая прибыль": "Tushum → tannarx → xarajatlar → sof foyda",
  "Выручка ↓": "Tushum ↓",
  "Выручка 30д": "Tushum 30k",
  "Выручка 90д": "Tushum 90k",
  "выручка может упасть на столько, прежде чем уйти в минус.": "minusga ketishdan oldin tushum shu darajada tushishi mumkin.",
  "выручка перейдёт с": "tushum quyidagidan o'tadi:",
  "Выручка по дням": "Kunlar bo'yicha tushum",
  "Выручка по месяцам (факт + прогноз)": "Oylar bo'yicha tushum (fakt + prognoz)",
  "Выручка по способам оплаты": "To'lov usullari bo'yicha tushum",
  "Выручка с каналов": "Kanallardan tushum",
  "Выручка сегодня": "Bugungi tushum",
  "Высокая (ширпотреб)": "Yuqori (ommaviy iste'mol mollari)",
  "Высокий B2C": "Yuqori B2C",
  "высота см": "balandlik sm",
  "Выход на 2 страны": "2 ta davlatga chiqish",
  "г": "g",
  "Где мы проигрываем": "Qayerda yutqazamiz",
  "Где теряем маржу?": "Marjani qayerda yo'qotyapmiz?",
  "Где у меня самая низкая маржа и что с этим делать?": "Eng past marja qayerda va u bilan nima qilish kerak?",
  "ген. директор": "bosh direktor",
  "Ген. директор": "Bosh direktor",
  "Генератор КП за 3 шага · УТП включено": "3 qadamda tijoriy taklif generatori · UTP kiritilgan",
  "Германия": "Germaniya",
  "Главный дашборд": "Asosiy dashbord",
  "Гонка продаж · 30 дней": "Sotuvlar poygasi · 30 kun",
  "готов помочь": "yordamga tayyor",
  "Готово": "Tayyor",
  "Готовые отчёты": "Tayyor hisobotlar",
  "График недоступен": "Grafik mavjud emas",
  "Группа A": "A guruh",
  "Группа B": "B guruh",
  "Группа C": "C guruh",
  "Дай мне сводку по бизнесу за прошлый месяц.": "Menga o'tgan oy uchun biznes bo'yicha xulosa ber.",
  "Дальше →": "Keyingisi →",
  "Дата": "Sana",
  "Дашборд": "Dashbord",
  "Дашборды по отделам · готовые отчёты": "Bo'limlar bo'yicha dashbordlar · tayyor hisobotlar",
  "Движение денег по дням · приход и расход · реальные данные": "Pul harakati kunlar bo'yicha · kirim va chiqim · haqiqiy ma'lumotlar",
  "Движение по дням": "Kunlar bo'yicha harakat",
  "Действие": "Harakat",
  "Действия": "Amallar",
  "Декабрь": "Dekabr",
  "Декор": "Dekor",
  "Деловой подарок CORP": "Ishbilarmon sovg'a CORP",
  "День рождения": "Tug'ilgan kun",
  "Дерево": "Yog'och",
  "Детракторы": "Detraktorlar",
  "Детракторы — звонить срочно": "Detraktorlar — zudlik bilan qo'ng'iroq qiling",
  "диаметр см": "diametr sm",
  "Дизайн-макет — данные ниже не настоящие": "Dizayn-maket — quyidagi ma'lumotlar haqiqiy emas",
  "Динамика NPS": "NPS dinamikasi",
  "Длина": "Uzunlik",
  "Для какой ЦА": "Qaysi auditoriya uchun",
  "для опта от 100 ед": "100 donadan ulgurji uchun",
  "Для финансовой модели нужны продажи хотя бы за месяц. Появятся данные — модель построится.": "Moliyaviy model uchun kamida bir oylik sotuvlar kerak. Ma'lumotlar paydo bo'lsa — model quriladi.",
  "дн": "kun",
  "дн назад": "kun oldin",
  "Дней до конца": "Oxirigacha kunlar",
  "до": "gacha",
  "До · во время · после покупки": "Oldin · vaqtida · keyin xarid",
  "до 200К/мес": "200K/oygacha",
  "До покупки": "Xariddan oldin",
  "Добавить": "Qo'shish",
  "Добавить свою единицу": "O'z birligingizni qo'shish",
  "Добавить тип": "Tur qo'shish",
  "добавлен": "qo'shildi",
  "добавлена": "qo'shildi",
  "Добавляется при создании товара": "Tovar yaratishda qo'shiladi",
  "добавьте расходы": "xarajatlarni qo'shing",
  "Добавьте сотрудников в разделе «Сотрудники».": "Xodimlarni «Xodimlar» bo'limida qo'shing.",
  "Договор": "Shartnoma",
  "долг": "qarz",
  "Долг": "Qarz",
  "Долг > 7 дней → SMS": "Qarz > 7 kun → SMS",
  "Долг клиента": "Mijoz qarzi",
  "Долг поставщику": "Yetkazib beruvchiga qarz",
  "Долги": "Qarzlar",
  "Долги клиентов": "Mijozlar qarzi",
  "Долгие ответы": "Uzoq javoblar",
  "Долго доставляли": "Uzoq yetkazishdi",
  "Долго едет": "Uzoq keladi",
  "Долгосрочно": "Uzoq muddatli",
  "Доля": "Ulush",
  "Доля в продажах": "Sotuvdagi ulush",
  "Дорого vs конкуренты": "Raqobatchilarga nisbatan qimmat",
  "Доставка": "Yetkazib berish",
  "Доставка 24ч": "24 soatda yetkazib berish",
  "Доставка 24ч · быстрее на 2 дня": "24 soatda yetkazib berish · 2 kun tezroq",
  "Другое": "Boshqa",
  "Дубликаты": "Dublikatlar",
  "Единая лента критических событий по всему бизнесу": "Butun biznes bo'yicha kritik hodisalarning yagona tasmasi",
  "единиц · можно добавлять свои": "birlik · o'zingiznikini qo'shishingiz mumkin",
  "Единиц получено": "Qabul qilingan donalar",
  "Единица": "Birlik",
  "Единицы измерения": "O'lchov birliklari",
  "Ежедневный сводный": "Kunlik yig'ma",
  "Если просрочка вынужденная — позвонить поставщику ДО срока, согласовать новый график.": "Agar kechikish majburiy bo'lsa — muddatdan OLDIN yetkazib beruvchiga qo'ng'iroq qiling, yangi jadvalni kelishing.",
  "есть задача-кандидат": "kandidat-vazifa bor",
  "Ещё не вышли в плюс в этом месяце": "Bu oyda hali plyusga chiqmadingiz",
  "Ж": "Ayol",
  "Ждёт от продавцов": "Sotuvchilardan kutilmoqda",
  "Ждут 24ч": "24s kutmoqda",
  "Журнал": "Jurnal",
  "за 30 дней": "30 kun ichida",
  "За выбранный период и фильтры продаж нет. Измените период или сбросьте фильтры.": "Tanlangan davr va filtrlar uchun sotuvlar yo'q. Davrni o'zgartiring yoki filtrlarni tozalang.",
  "за месяц": "oy uchun",
  "за неделю": "hafta uchun",
  "За последний месяц не было продаж — симулятору не на чём строить baseline. Появятся продажи — прогноз заработает.": "Oxirgi oyda sotuvlar bo'lmagan — simulyatorga baseline qurish uchun asos yo'q. Sotuvlar paydo bo'lsa — prognoz ishlaydi.",
  "за смену": "smena uchun",
  "Заголовок": "Sarlavha",
  "Заголовок / тема": "Sarlavha / mavzu",
  "Заголовок обязателен": "Sarlavha majburiy",
  "Загрузка...": "Yuklanmoqda...",
  "Задаёт вопросы": "Savollar beradi",
  "Задача CRM": "CRM vazifasi",
  "задокументировано": "hujjatlashtirilgan",
  "заказов": "buyurtma",
  "Заказов на клиента": "Mijozga buyurtmalar",
  "Заказы поставщикам · 24ч подтверждение · авто-замена": "Yetkazib beruvchilarga buyurtmalar · 24s tasdiqlash · avto-almashtirish",
  "Заканчиваются": "Tugayapti",
  "Закрепление в Ташкенте": "Toshkentda mustahkamlanish",
  "Закрыть": "Yopish",
  "Закупить «Брус 50×100» сейчас": "«Brus 50×100» ni hozir xarid qilish",
  "Закупка": "Xarid",
  "Закупки": "Xaridlar",
  "залетело": "muvaffaqiyatli",
  "Заметное повышение маржи": "Marjani sezilarli oshirish",
  "Запас на 4 дня. Не закажете до завтра — потеряете 8.5M.": "Zaxira 4 kunga. Ertangacha buyurtma bermasangiz — 8.5M yo'qotasiz.",
  "Запас прочности —": "Mustahkamlik zaxirasi —",
  "Запись 1": "Yozuv 1",
  "Запись 2": "Yozuv 2",
  "Запланировать": "Rejalashtirish",
  "Запланировать первую": "Birinchisini rejalashtirish",
  "Запланируй хотя бы 5 публикаций на ближайшую неделю — Reels, посты, истории. Контент-план превращает «я не успеваю» в «у меня всё по графику».": "Yaqin hafta uchun kamida 5 ta nashrni rejalashtiring — Reels, postlar, story. Kontent-reja «ulgurmayapman» ni «hammasi jadval bo'yicha» ga aylantiradi.",
  "Заполните все поля": "Barcha maydonlarni to'ldiring",
  "Запуск авто-слияния": "Avto-birlashtirish ishga tushirildi",
  "Запуск инвентаризации": "Inventarizatsiyani ishga tushirish",
  "Запусков": "Ishga tushishlar",
  "Запусков (мес)": "Ishga tushishlar (oy)",
  "Запустить новую инвентаризацию": "Yangi inventarizatsiyani ishga tushirish",
  "Запустить B2B-канал": "B2B-kanalni ishga tushirish",
  "зарегистрирован": "ro'yxatga olindi",
  "Зарегистрированы < 30 дней назад": "30 kundan kam vaqt oldin ro'yxatdan o'tgan",
  "Зарплаты": "Ish haqi",
  "Засыпает": "Uxlamoqda",
  "Затишье B2C, активный B2B": "B2C sokin, B2B faol",
  "Защита от ошибок ввода · дубликаты · валидация": "Kiritish xatolaridan himoya · dublikatlar · validatsiya",
  "Звонок": "Qo'ng'iroq",
  "Звонок инициирован:": "Qo'ng'iroq boshlandi:",
  "здесь видно, что продаётся в реальном времени.": "bu yerda nima real vaqtda sotilayotgani ko'rinadi.",
  "Здоровая": "Sog'lom",
  "Здоровая маржа": "Sog'lom marja",
  "Идёт инвентаризация...": "Inventarizatsiya ketmoqda...",
  "из": "dan",
  "из 12": "12 dan",
  "Изменение цен в процентах": "Narxlarni foizda o'zgartirish",
  "Изменение цен по всему ассортименту:": "Butun assortiment bo'yicha narxlarni o'zgartirish:",
  "Изменения сохранены": "O'zgarishlar saqlandi",
  "Изоляция компаний": "Kompaniyalarni izolyatsiya qilish",
  "Изоляция филиалов": "Filiallarni izolyatsiya qilish",
  "Изучает каталог": "Katalogni o'rganadi",
  "Импорт XLSX — в разработке": "XLSX import — ishlab chiqilmoqda",
  "Инвентаризация завершена · 18 расхождений найдено": "Inventarizatsiya yakunlandi · 18 ta tafovut topildi",
  "Инсайтов": "Insaytlar",
  "Интерес": "Qiziqish",
  "Интерпретация:": "Talqin:",
  "Инфо": "Ma'lumot",
  "Информация": "Ma'lumot",
  "Использование": "Foydalanish",
  "Использует": "Foydalanadi",
  "Используется в": "Quyidagida ishlatiladi:",
  "История взаимодействий": "O'zaro aloqalar tarixi",
  "Источник клиентов не заполнен": "Mijozlar manbasi to'ldirilmagan",
  "Июль": "Iyul",
  "Июнь": "Iyun",
  "Йогоч ваза 45": "Yog'och vaza 45",
  "к прошлому периоду": "o'tgan davrga nisbatan",
  "К сборке": "Yig'ishga",
  "к сведению": "ma'lumot uchun",
  "Каждый запрос фильтруется по вашей компании — чужие данные недоступны": "Har bir so'rov sizning kompaniyangiz bo'yicha filtrlanadi — begona ma'lumotlar mavjud emas",
  "Как защищена система": "Tizim qanday himoyalangan",
  "Как мотивировать команду продаж?": "Sotuv jamoasini qanday rag'batlantirish kerak?",
  "Как настроить программу лояльности для VIP?": "VIP uchun sodiqlik dasturini qanday sozlash kerak?",
  "Как только кассир проведёт продажу — она появится здесь.": "Kassir sotuvni amalga oshirishi bilan u bu yerda paydo bo'ladi.",
  "Как только появятся приходы/расходы в кассе — поток отобразится здесь.": "Kassada kirim/chiqim paydo bo'lishi bilan oqim shu yerda ko'rsatiladi.",
  "Как улучшить мою прибыль на 10%?": "Foydamni 10% ga qanday oshirish mumkin?",
  "Как это считается": "Bu qanday hisoblanadi",
  "Какие товары закупить?": "Qaysi tovarlarni xarid qilish kerak?",
  "Какие товары мёртвые — куда отнести скидку?": "Qaysi tovarlar o'lik — chegirmani qayerga qo'yish kerak?",
  "Какие цены пересмотреть и почему?": "Qaysi narxlarni qayta ko'rib chiqish kerak va nega?",
  "Какой риск если этого не сделаю?": "Agar buni qilmasam, qanday xavf bor?",
  "Какой риск, если я этого не сделаю?": "Agar buni qilmasam, qanday xavf bor?",
  "Какой триггер должен случиться чтобы стало актуально?": "Dolzarb bo'lishi uchun qanday trigger yuz berishi kerak?",
  "Какой филиал лидер и кто отстаёт?": "Qaysi filial yetakchi va kim orqada qolmoqda?",
  "Кампания": "Kampaniya",
  "Канал": "Kanal",
  "Каналы": "Kanallar",
  "Каналы — где живёт": "Kanallar — qayerda yashaydi",
  "Каналы привлечения": "Jalb qilish kanallari",
  "кандидаты на ликвидацию": "tugatishga nomzodlar",
  "Карта Ташкента": "Toshkent xaritasi",
  "Карточки · история покупок · долги": "Kartochkalar · xaridlar tarixi · qarzlar",
  "Карусель": "Karusel",
  "Касса": "Kassa",
  "Касса / онлайн": "Kassa / onlayn",
  "кассир": "kassir",
  "Кассир": "Kassir",
  "Кастомные поля по типу товара": "Tovar turi bo'yicha maxsus maydonlar",
  "Каталог": "Katalog",
  "Каталог · поиск · фильтры · добавление": "Katalog · qidiruv · filtrlar · qo'shish",
  "Каталог · цены · фото · штрих-коды · печать ценников": "Katalog · narxlar · foto · shtrix-kodlar · narx yorliqlari chop etish",
  "Категории каталога": "Katalog kategoriyalari",
  "категорий товаров": "tovar toifalari",
  "Качество": "Sifat",
  "Квалификация": "Kvalifikatsiya",
  "кг": "kg",
  "Керамика": "Keramika",
  "Клиент": "Mijoz",
  "клиентов": "mijoz",
  "Клиентов": "Mijozlar",
  "клиентов ≥2 заказов": "≥2 buyurtmali mijozlar",
  "клиентов в сегменте": "segmentdagi mijozlar",
  "Клиентская база": "Mijozlar bazasi",
  "Клиенты": "Mijozlar",
  "клиенты уйдут": "mijozlar ketadi",
  "Когда": "Qachon",
  "Когда выходишь в плюс · текущий месяц · реальные данные": "Qachon plyusga chiqasiz · joriy oy · haqiqiy ma'lumotlar",
  "Кого из спящих клиентов вернуть в первую очередь?": "Uxlab yotgan mijozlardan kimni birinchi navbatda qaytarish kerak?",
  "Кол-во": "Soni",
  "Кол-во 90д": "Soni 90k",
  "Количество": "Miqdor",
  "Команда по ролям": "Jamoa rollar bo'yicha",
  "Комменты": "Izohlar",
  "Коммерческое предложение": "Tijoriy taklif",
  "Компания": "Kompaniya",
  "компл": "to'plam",
  "компонентов": "komponent",
  "Конверсия": "Konversiya",
  "Конк. A": "Raqobatchi A",
  "Конк. B": "Raqobatchi B",
  "Конкретно у кого? Сравним по 5 параметрам — часто разница в качестве.": "Aniq kimda? 5 parametr bo'yicha solishtiramiz — ko'pincha farq sifatda.",
  "Конкурентов": "Raqobatchilar",
  "Конструктор курса": "Kurs konstruktori",
  "Конструктор набора": "To'plam konstruktori",
  "Конструктор сценария": "Stsenariy konstruktori",
  "Копировать": "Nusxalash",
  "коробка": "quti",
  "Корпоративный pipeline · PITCH · тарифы": "Korporativ pipeline · PITCH · tariflar",
  "КП": "Tijoriy taklif",
  "КП готово!": "Tijoriy taklif tayyor!",
  "КП отправлено": "Tijoriy taklif yuborildi",
  "Критично": "Kritik",
  "Критичные": "Kritik",
  "критичных": "kritik",
  "Кто и сколько должен · кому пора звонить": "Kim qancha qarzdor · kimga qo'ng'iroq qilish kerak",
  "Купили": "Sotib olishdi",
  "Курс — последний использованный в операциях (кассир вводит уличный курс при продаже).": "Kurs — operatsiyalarda oxirgi ishlatilgan (kassir sotuvda ko'cha kursini kiritadi).",
  "Курсов": "Kurslar",
  "Курсы in-app · уроки · аттестация": "Ilova ichidagi kurslar · darslar · attestatsiya",
  "Курьеров": "Kuryerlar",
  "курьеров онлайн · обновление 30 сек": "kuryer onlayn · yangilanish 30 sek",
  "Курьеры · карта · статусы доставки": "Kuryerlar · xarita · yetkazish statuslari",
  "Кэшбек 5%": "5% keshbek",
  "л": "l",
  "Лайки": "Layklar",
  "Латун шамдон × 1 · 580K UZS": "Latun shamdon × 1 · 580K UZS",
  "Латунь": "Jez",
  "Лёгкое стимулирование спроса": "Talabni yengil rag'batlantirish",
  "Лид": "Lid",
  "Лидер месяца": "Oy lideri",
  "Лидерборд построится, как только сотрудники начнут продавать.": "Liderbord xodimlar sota boshlashi bilan tuziladi.",
  "Лидерборд продаж за 30 дней · реальные результаты": "30 kunlik sotuv liderbordi · haqiqiy natijalar",
  "Лидов": "Lidlar",
  "Лидов (мес)": "Lidlar (oy)",
  "Личный менеджер": "Shaxsiy menejer",
  "Личный менеджер для B2B": "B2B uchun shaxsiy menejer",
  "Локальные посредники": "Mahalliy vositachilar",
  "Лояльность": "Sodiqlik",
  "Лояльность · детракторы · действия": "Sodiqlik · detraktorlar · amallar",
  "Лучший канал": "Eng yaxshi kanal",
  "Любой": "Har qanday",
  "Любые наблюдения о ЦА": "Auditoriya haqida har qanday kuzatishlar",
  "м": "m",
  "М": "Erkak",
  "м²": "m²",
  "м³": "m³",
  "Май": "May",
  "Максимум": "Maksimum",
  "мало": "kam",
  "Мар": "Mar",
  "Маржа": "Marja",
  "Маржа ↑": "Marja ↑",
  "Маржа ↓": "Marja ↓",
  "маржа 41.6%": "marja 41.6%",
  "Маржа набора": "To'plam marjasi",
  "Маржа по дням": "Kunlar bo'yicha marja",
  "Маржа по каждому товару · приоритет проблемных": "Har bir tovar bo'yicha marja · muammolilar ustuvor",
  "Маржа по категориям": "Kategoriyalar bo'yicha marja",
  "Маржинальность": "Marjinallik",
  "Маркетинг": "Marketing",
  "Маркетплейсы": "Marketpleyslar",
  "Маркетплейсы UZ": "UZ marketpleyslar",
  "Март": "Mart",
  "материал": "material",
  "Матрица Эйзенхауэра — задачи дня": "Eyzenxauer matritsasi — kun vazifalari",
  "Матрица Эйзенхауэра · ССП · ORG · бизнес-процессы": "Eyzenxauer matritsasi · SSP · ORG · biznes-jarayonlar",
  "Матрица ABC × XYZ": "ABC × XYZ matritsasi",
  "Медианный LTV": "Median LTV",
  "Международные выставки": "Xalqaro ko'rgazmalar",
  "менеджер": "menejer",
  "Менеджер": "Menejer",
  "Менеджер видит только свой филиал — проверяется на сервере": "Menejer faqat o'z filialini ko'radi — serverda tekshiriladi",
  "меньше 2 месяцев": "2 oydan kam",
  "Меньший ассортимент дерева": "Yog'och assortimenti kamroq",
  "Меняется при создании товара": "Tovar yaratishda o'zgaradi",
  "Мёртвые (CZ)": "O'lik (CZ)",
  "Мёртвый товар — ликвидация со скидкой": "O'lik tovar — chegirma bilan tugatish",
  "мес": "oy",
  "Месяц": "Oy",
  "месяца.": "oyning.",
  "Метрики: план vs факт": "Ko'rsatkichlar: reja vs fakt",
  "мл": "ml",
  "модулей": "modul",
  "Молодая мама 25-35 / Студент / Прораб...": "Yosh ona 25-35 / Talaba / Prorab...",
  "монитор для руководителя": "rahbar uchun monitor",
  "Мониторинг цен · сильные/слабые стороны": "Narxlar monitoringi · kuchli/zaif tomonlar",
  "му числу": "-sanasiga",
  "Мы": "Biz",
  "на": "ga",
  "на 2026": "2026 uchun",
  "на основе фактических месяцев. Расходы прогнозируются по среднему уровню.": "haqiqiy oylar asosida. Chiqimlar o'rtacha daraja bo'yicha prognoz qilinadi.",
  "Набор": "To'plam",
  "Наборов": "To'plamlar",
  "Название": "Nomi",
  "Название (русский)": "Nomi (ruscha)",
  "Название (RU)": "Nomi (RU)",
  "Название обязательно": "Nomi majburiy",
  "Название типа": "Tur nomi",
  "Найденные дубликаты (требуют слияния)": "Topilgan dublikatlar (birlashtirishni talab qiladi)",
  "Напиши вопрос... (Enter — отправить, Shift+Enter — новая строка)": "Savol yozing... (Enter — yuborish, Shift+Enter — yangi qator)",
  "например: бухта, моток, тюк": "masalan: buxta, kalava, tyuk",
  "Например: оплата аренды": "Masalan: ijara to'lovi",
  "Например: продажа клиенту X": "Masalan: X mijozga sotuv",
  "Например: Электроника": "Masalan: Elektronika",
  "Например: Adidas": "Masalan: Adidas",
  "Настройки": "Sozlamalar",
  "Начать заново": "Qaytadan boshlash",
  "Начнём заново. Что тебя интересует?": "Qaytadan boshlaymiz. Sizni nima qiziqtiradi?",
  "Наш бонус": "Bizning bonus",
  "Наше УТП — встраивается в каждое КП": "Bizning UTP — har bir taklifga kiritiladi",
  "Наши сильные стороны": "Bizning kuchli tomonlarimiz",
  "НГ-распродажи": "Yangi yil chegirmalari",
  "не зашло": "ishlamadi",
  "Не назначен": "Tayinlanmagan",
  "Не подключена": "Ulanmagan",
  "Не получил ответ. Попробуй переформулировать.": "Javob olmadim. Boshqacha ifodalashga harakat qiling.",
  "Не получилось связаться с AI. Попробуй ещё раз.": "AI bilan bog'lanib bo'lmadi. Yana urinib ko'ring.",
  "Не понимает разницу с конкурентами": "Raqobatchilar bilan farqni tushunmaydi",
  "Не продаётся 47 дней. Освободит 8.5M оборотки.": "47 kundan beri sotilmayapti. 8.5M aylanma mablag'ni bo'shatadi.",
  "Не разобрался": "Tushunib yetmadi",
  "Не тот цвет": "Rang noto'g'ri",
  "Не удалось связаться с AI. Попробуй ещё раз.": "AI bilan bog'lanib bo'lmadi. Yana urinib ko'ring.",
  "не указан": "ko'rsatilmagan",
  "не указана": "ko'rsatilmagan",
  "Невыгодно": "Foydasiz",
  "Неделя": "Hafta",
  "Недостаточно данных для прогноза": "Prognoz uchun ma'lumot yetarli emas",
  "Недостаточно истории": "Tarix yetarli emas",
  "Нейтралы": "Neytrallar",
  "непогашено": "to'lanmagan",
  "Непредсказуемый середняк — гибкий запас": "Bashoratsiz o'rtacha tovar — moslashuvchan zaxira",
  "НЕСРОЧНО · ВАЖНО": "SHOSHILINCH EMAS · MUHIM",
  "НЕСРОЧНО · НЕВАЖНО": "SHOSHILINCH EMAS · MUHIM EMAS",
  "нет": "yo'q",
  "Нет": "Yo'q",
  "Нет атрибутов": "Atributlar yo'q",
  "Нет брендов": "Brendlar yo'q",
  "Нет в наличии": "Mavjud emas",
  "Нет данных": "Ma'lumot yo'q",
  "Нет данных за период": "Davr uchun ma'lumot yo'q",
  "Нет движений по кассе за период": "Davr uchun kassada harakat yo'q",
  "Нет долгов": "Qarzlar yo'q",
  "Нет долгов в этой категории": "Bu kategoriyada qarzlar yo'q",
  "Нет долгов поставщикам": "Yetkazib beruvchilarga qarz yo'q",
  "Нет должников": "Qarzdorlar yo'q",
  "Нет единиц": "Birliklar yo'q",
  "Нет клиентов в этом сегменте": "Bu segmentda mijozlar yo'q",
  "Нет продаж за месяц": "Oy uchun sotuvlar yo'q",
  "Нет рассрочки 3/6/12": "3/6/12 bo'lib to'lash yo'q",
  "Нет типов": "Turlar yo'q",
  "Нет товаров": "Tovarlar yo'q",
  "Нет точек в Самарканде/Бухаре": "Samarqand/Buxoroda nuqtalar yo'q",
  "Нет чатов": "Chatlar yo'q",
  "Низкая (уникальный товар)": "Past (noyob tovar)",
  "Низкая маржа": "Past marja",
  "Низкая маржа в категории «Одежда» (18%) — конкуренты делают аналог за меньшую цену. Поднять цену нельзя. Решение: перейти к локальным брендам с маржой 35%.": "«Kiyim» kategoriyasida past marja (18%) — raqobatchilar o'xshashini arzonroq narxda taklif qiladi. Narxni oshirib bo'lmaydi. Yechim: 35% marjali mahalliy brendlarga o'tish.",
  "Низкий вклад · средние колебания": "Past hissa · o'rtacha tebranishlar",
  "Низкий остаток → Заказ": "Past qoldiq → Buyurtma",
  "Ничего не найдено": "Hech narsa topilmadi",
  "Новая публикация": "Yangi nashr",
  "Новички": "Yangilar",
  "Новогодние подарки → сезон": "Yangi yil sovg'alari → mavsum",
  "Новогодний": "Yangi yil to'plami",
  "Новые": "Yangi",
  "новые продажи": "yangi sotuvlar",
  "Новые товары": "Yangi tovarlar",
  "Новый": "Yangi",
  "Новый бренд": "Yangi brend",
  "Новый бренд Karven": "Yangi brend Karven",
  "Новый дашборд": "Yangi dashbord",
  "Новый заказ": "Yangi buyurtma",
  "Новый портрет ЦА": "Yangi auditoriya portreti",
  "Новый приход": "Yangi kirim",
  "Новый сезон": "Yangi mavsum",
  "Новый тип": "Yangi tur",
  "Новый товар": "Yangi tovar",
  "Новый филиал добавляется через раздел «Персонал → Сотрудники» или администратором системы.": "Yangi filial «Xodimlar → Xodimlar» bo'limi orqali yoki tizim administratori tomonidan qo'shiladi.",
  "Новый чат": "Yangi chat",
  "Ноябрь": "Noyabr",
  "Нужен аккаунт Eskiz.uz. Подключим по запросу — напишите нам.": "Eskiz.uz akkaunti kerak. So'rov bo'yicha ulaymiz — bizga yozing.",
  "Нужен доступ к интернет-банку компании. Подключим по запросу.": "Kompaniyaning internet-bankiga kirish kerak. So'rov bo'yicha ulaymiz.",
  "Нужен кабинет продавца на маркетплейсе и API-ключ. Есть — напишите нам.": "Marketpleysda sotuvchi kabineti va API-kalit kerak. Bo'lsa — bizga yozing.",
  "Нужен мерчант-договор с провайдером (даёт ключи). Есть договор — напишите нам, подключим.": "Provayder bilan merchant-shartnoma kerak (kalitlarni beradi). Shartnoma bo'lsa — bizga yozing, ulaymiz.",
  "Нужны токен и chat_id": "Token va chat_id kerak",
  "обжиг": "kuydirish",
  "Общий результат": "Umumiy natija",
  "Общий LTV": "Umumiy LTV",
  "Общий ROI": "Umumiy ROI",
  "Объединено": "Birlashtirildi",
  "Объём": "Hajm",
  "обязательное поле": "majburiy maydon",
  "Одежда": "Kiyim",
  "Октябрь": "Oktyabr",
  "Онлайн-оплата": "Onlayn to'lov",
  "операций": "operatsiya",
  "Операций пока нет": "Hozircha operatsiyalar yo'q",
  "Описание": "Tavsif",
  "описаны pain points": "pain pointlar tavsiflangan",
  "Опиши своих покупателей: кто они, что хотят, что им мешает купить": "Xaridorlaringizni ta'riflang: ular kim, nima istaydi, sotib olishga nima xalaqit beradi",
  "Опиши хотя бы 3 портрета — это база любого маркетинга. Кто твой покупатель? Что у него болит? Где он живёт онлайн? Это поможет писать контент, скрипты продаж и таргет.": "Kamida 3 ta portretni ta'riflang — bu har qanday marketingning asosi. Sizning xaridoringiz kim? Uni nima qiynaydi? U onlaynda qayerda yashaydi? Bu kontent, sotuv skriptlari va targetni yozishga yordam beradi.",
  "Оплата": "To'lov",
  "Оплатить срочно — иначе поставщик может отказаться от следующих поставок или поднять цены.": "Zudlik bilan to'lang — aks holda yetkazib beruvchi keyingi yetkazishlardan voz kechishi yoki narxlarni oshirishi mumkin.",
  "Оплачено": "To'langan",
  "Оплачивает": "To'laydi",
  "Опрос «что пошло не так» · попытка last-chance с агрессивной скидкой": "«Nima noto'g'ri ketdi» so'rovi · agressiv chegirma bilan last-chance urinishi",
  "Опрос запущен на 245 клиентов": "So'rovnoma 245 mijozga ishga tushirildi",
  "Остаток": "Qoldiq",
  "От поставщиков · на склад": "Yetkazib beruvchilardan · omborga",
  "От поставщиков · оплата · долги": "Yetkazib beruvchilardan · to'lov · qarzlar",
  "Ответственный": "Mas'ul",
  "отвечает за час": "bir soatda javob beradi",
  "Отключить": "Uzish",
  "Откройте своего бота и нажмите «Старт» (или добавьте в группу)": "Botingizni oching va «Start» bosing (yoki guruhga qo'shing)",
  "Открыт курс": "Kurs ochildi",
  "Открыта детализация": "Tafsilotlar ochildi",
  "Открыта карточка": "Karta ochildi",
  "Открыта карточка набора": "To'plam kartasi ochildi",
  "Открыта форма новой сделки": "Yangi bitim formasi ochildi",
  "Открыта форма создания сделки": "Bitim yaratish shakli ochildi",
  "Открытка от руки": "Qo'lda yozilgan otkritka",
  "Открытый вопрос — заставляет клиента думать. «Что для вас важнее: цена или качество?»": "Ochiq savol — mijozni o'ylashga majbur qiladi. «Siz uchun nima muhimroq: narx yoki sifat?»",
  "Открытых": "Ochiq",
  "Открыть 3 филиала": "3 ta filial ochish",
  "Откуда приходят клиенты · ROI каждого канала · LTV по источнику": "Mijozlar qayerdan keladi · har bir kanal ROI · manba bo'yicha LTV",
  "Отложено": "Keyinga qoldirildi",
  "Отмена": "Bekor qilish",
  "Отметить опубликованным": "Chop etilgan deb belgilash",
  "Отправить": "Yuborish",
  "Отправить email": "Email yuborish",
  "Отправлена акция «Весна-2026»": "«Bahor-2026» aksiyasi yuborildi",
  "Отправлено": "Yuborildi",
  "Отправлено в Telegram ✓": "Telegramga yuborildi ✓",
  "п.п.": "f.p.",
  "Падение продаж мужской одежды в мае на 18% связано с: 1) уход из ассортимента бренда X · 2) высокий сезон конкурентов · 3) ваш Instagram перешёл на другие категории.": "May oyida erkaklar kiyimi sotuvining 18% pasayishi quyidagilar bilan bog'liq: 1) X brendining assortimentdan chiqishi · 2) raqobatchilarning yuqori mavsumi · 3) Instagramingiz boshqa kategoriyalarga o'tdi.",
  "Пайплайн": "Payplayn",
  "пара": "juft",
  "Пароли": "Parollar",
  "Партнёры": "Hamkorlar",
  "пачка": "pachka",
  "Переговоры": "Muzokaralar",
  "Переход на сайт": "Saytga o'tish",
  "Период": "Davr",
  "Персональный звонок · эксклюзивные предложения · приоритетная поддержка": "Shaxsiy qo'ng'iroq · eksklyuziv takliflar · ustuvor qo'llab-quvvatlash",
  "Пик НГ · 31 декабря": "Yangi yil cho'qqisi · 31 dekabr",
  "Письмо": "Xat",
  "план": "reja",
  "План": "Reja",
  "план действий": "harakatlar rejasi",
  "План мес.": "Oylik reja",
  "План продаж · план закупок · бюджет": "Sotuv rejasi · xarid rejasi · byudjet",
  "План просмотров:": "Ko'rishlar rejasi:",
  "План vs Факт (5 мес)": "Reja vs Fakt (5 oy)",
  "Платформа": "Platforma",
  "Площадь": "Maydon",
  "По категориям": "Toifalar bo'yicha",
  "по компонентам": "komponentlar bo'yicha",
  "По отделам": "Bo'limlar bo'yicha",
  "по реальным операциям": "haqiqiy operatsiyalar bo'yicha",
  "По способам оплаты": "To'lov usullari bo'yicha",
  "По текущей динамике (средний чистый поток": "Joriy dinamika bo'yicha (o'rtacha sof oqim",
  "По текущему темпу в этом месяце выйти в плюс не успеваете — нужно ускорять продажи или снижать постоянные расходы.": "Joriy sur'at bo'yicha bu oyda plyusga chiqishga ulgurmaysiz — sotuvlarni tezlashtirish yoki doimiy chiqimlarni kamaytirish kerak.",
  "По текущему темпу выйдете в плюс примерно к": "Joriy sur'at bo'yicha taxminan shu sanaga plyusga chiqasiz",
  "по числу товаров": "tovarlar soni bo'yicha",
  "По Telegram": "Telegram orqali",
  "Повторить": "Qayta urinish",
  "Повторные": "Takroriy",
  "Повторные покупки": "Takroriy xaridlar",
  "Подарки 8 марта": "8 mart sovg'alari",
  "Подарок": "Sovg'a",
  "Подготовка к НГ": "Yangi yilga tayyorgarlik",
  "Подключается администратором системы — напишите нам, если нужна в первую очередь.": "Tizim administratori tomonidan ulanadi — agar birinchi navbatda kerak bo'lsa, bizga yozing.",
  "Подключается по запросу — напишите нам.": "So'rov bo'yicha ulanadi — bizga yozing.",
  "Подключение и синхронизация внешних сервисов": "Tashqi xizmatlarni ulash va sinxronizatsiya",
  "Подключение…": "Ulanmoqda…",
  "Подключить": "Ulash",
  "Поднять +15%": "Ko'tarish +15%",
  "Поднять +25%": "Ko'tarish +25%",
  "Поднять +5%": "Ko'tarish +5%",
  "Поднять цену на «Шахматы 40×40» на 12%": "«Shaxmat 40×40» narxini 12% oshirish",
  "Подписки": "Obunalar",
  "Подсказки": "Maslahatlar",
  "Подсказки:": "Maslahatlar:",
  "Подтвердить до": "Tasdiqlash muddati",
  "Позвонить": "Qo'ng'iroq qilish",
  "Позвонить лично · отправить SMS с напоминанием · согласовать новый срок и заплатить частично сейчас.": "Shaxsan qo'ng'iroq qiling · eslatma SMS yuboring · yangi muddatni kelishing va hozir qisman to'lang.",
  "Позже": "Keyinroq",
  "позиций": "pozitsiya",
  "Позиций": "Pozitsiyalar",
  "Позиция": "Pozitsiya",
  "Поиск по продажам": "Sotuvlar bo'yicha qidiruv",
  "Пока нет покупателей с привязкой к клиенту": "Hozircha mijozga bog'langan xaridorlar yo'q",
  "Пока нет участников": "Hozircha ishtirokchilar yo'q",
  "Пока пусто": "Hozircha bo'sh",
  "Покажи конкретные шаги": "Aniq qadamlarni ko'rsat",
  "Показаны первые 100 из": "Birinchi 100 tasi ko'rsatildi, jami",
  "Показаны первые 200 из": "Birinchi 200 tasi ko'rsatildi, jami",
  "Показаны первые 300 из": "Birinchi 300 tasi ko'rsatildi, jami",
  "Показаны последние 300 продаж. Уточните период или фильтры для более точного среза.": "Oxirgi 300 ta sotuv ko'rsatildi. Aniqroq kesim uchun davr yoki filtrlarni aniqlashtiring.",
  "Показать историю": "Tarixni ko'rsatish",
  "покрытие": "qoplama",
  "покрытия": "qoplash",
  "покупателей": "xaridor",
  "Покупка": "Xarid",
  "Покупка → Бонус через 7д": "Xarid → 7 kundan keyin bonus",
  "пол": "jins",
  "Пол": "Jins",
  "Получение": "Olish",
  "Пользователей": "Foydalanuvchilar",
  "Понедельник недельный": "Dushanba haftalik",
  "порода": "nav",
  "Портретов ЦА ещё нет": "Hali auditoriya portretlari yo'q",
  "Посл. покупка": "Oxirgi xarid",
  "После покупки": "Xariddan keyin",
  "Последние продажи": "Oxirgi sotuvlar",
  "Последняя": "Oxirgi",
  "Пост": "Post",
  "Поставщик": "Yetkazib beruvchi",
  "Поставщиков": "Yetkazib beruvchilar",
  "Постоянные должники": "Doimiy qarzdorlar",
  "Постоянные расходы": "Doimiy chiqimlar",
  "Постоянные расходы берутся из кассовых расходов за месяц, маржинальность — из продаж (выручка минус себестоимость).": "Doimiy chiqimlar oylik kassa chiqimlaridan olinadi, marjinallik — sotuvlardan (tushum minus tannarx).",
  "Постоянный": "Doimiy",
  "Потеря продаж": "Sotuvlar yo'qotilishi",
  "Потерян": "Yo'qotilgan",
  "Почему продажи упали?": "Nega sotuvlar tushdi?",
  "Правил": "Qoidalar",
  "Превентивный SMS за 3-5 дней до срока — снижает просрочку на 60%.": "Muddatdan 3-5 kun oldin profilaktik SMS — kechikishni 60% kamaytiradi.",
  "При изменении цен на": "Narxlarni o'zgartirishda",
  "Прибыль": "Foyda",
  "Прибыль / мес (факт)": "Foyda / oy (fakt)",
  "Прибыль с единицы": "Birlik foydasi",
  "Прибыльно, но риск оттока": "Foydali, lekin ketish xavfi bor",
  "Привет! Я твой AI-консультант по бизнесу. Спроси что-нибудь или выбери вопрос ниже.": "Salom! Men sizning biznes bo'yicha AI-maslahatchingizman. Biror narsa so'rang yoki quyidagi savolni tanlang.",
  "Привет! Я AI-консультант по бизнесу. Спроси что-нибудь или выбери вопрос ниже.": "Salom! Men biznes bo'yicha AI-maslahatchiman. Biror narsa so'rang yoki quyidagi savolni tanlang.",
  "привлечение": "jalb qilish",
  "привязаны к типам": "turlarga bog'langan",
  "Приглашённых": "Taklif qilinganlar",
  "Прим": "Izoh",
  "Применено": "Qo'llanildi",
  "Применено!": "Qo'llanildi!",
  "Применить": "Qo'llash",
  "Примечание": "Izoh",
  "Принято": "Qabul qilindi",
  "Прирост продаж": "Sotuvlar o'sishi",
  "Приход": "Kirim",
  "Приход · расход по методам оплаты": "Kirim · chiqim to'lov usullari bo'yicha",
  "Приход (день)": "Kirim (kun)",
  "Приход (период)": "Kirim (davr)",
  "Приход денег": "Pul kirimi",
  "Приход, расход и баланс по 10 валютам": "Kirim, chiqim va balans 10 valyutada",
  "приходов": "kirim",
  "Прицельный пушинг к сделке. «Тогда у нас есть именно то что вам нужно — берём?»": "Bitimga aniq turtki. «Unda bizda aynan sizga kerak narsa bor — olamizmi?»",
  "прогноз": "prognoz",
  "Прогноз": "Prognoz",
  "Прогноз баланса на 7 дней": "7 kunlik balans prognozi",
  "Прогноз выручки": "Tushum prognozi",
  "Прогноз строится по среднемесячному темпу роста": "Prognoz o'rtacha oylik o'sish sur'ati bo'yicha quriladi",
  "Прогресс": "Progress",
  "продавали за 30 дней": "30 kun ichida sotgan",
  "Продавали за 30 дней": "30 kun ichida sotgan",
  "продавец": "sotuvchi",
  "Продавец": "Sotuvchi",
  "продаж": "sotuv",
  "Продаж / мес": "Sotuvlar / oy",
  "Продаж 30д": "Sotuvlar 30k",
  "продаж могут уйти из-за чувствительности к цене.": "sotuv narxga sezgirlik tufayli yo'qolishi mumkin.",
  "Продаж не найдено": "Sotuvlar topilmadi",
  "продаж по среднему чеку": "o'rtacha chek bo'yicha sotuv",
  "продаж с непогашенным долгом — проверьте раздел": "to'lanmagan qarzli sotuv — bo'limni tekshiring",
  "продаж.": "sotuv.",
  "продажа": "sotuv",
  "Продажа": "Sotuv",
  "Продажи": "Sotuvlar",
  "Продажи 101": "Sotuvlar 101",
  "Продажи за период": "Davr uchun sotuvlar",
  "Продажи команды 30д": "Jamoa sotuvlari 30k",
  "Продажи смены появятся здесь в реальном времени.": "Smena sotuvlari bu yerda real vaqtda paydo bo'ladi.",
  "Продажи, маржа и эффективность сотрудников": "Sotuvlar, marja va xodimlar samaradorligi",
  "Производители · доля в продажах": "Ishlab chiqaruvchilar · sotuvdagi ulush",
  "Произвольный период": "Ixtiyoriy davr",
  "Промо: «Косметика» −25%": "Promo: «Kosmetika» −25%",
  "Промоутеры": "Promouterlar",
  "Просмотры": "Ko'rishlar",
  "Просрочен": "Muddati o'tgan",
  "Просроченные": "Muddati o'tganlar",
  "просрочено": "muddati o'tgan",
  "Просрочено": "Muddati o'tgan",
  "Просрочки": "Kechikishlar",
  "Процессы": "Jarayonlar",
  "Прочее": "Boshqa",
  "прошлый": "o'tgan",
  "Прошлый период пуст — сравнение появится позже": "O'tgan davr bo'sh — solishtirish keyinroq paydo bo'ladi",
  "Публикаций ещё нет": "Hali nashrlar yo'q",
  "Пустой ответ от AI.": "AI-dan bo'sh javob keldi.",
  "Путь клиента · 7 этапов · точки боли · бонусы": "Mijoz yo'li · 7 bosqich · og'riq nuqtalari · bonuslar",
  "работают в системе": "tizimda ishlaydi",
  "размер (S/M/L/XL)": "o'lcham (S/M/L/XL)",
  "разных": "xil",
  "разобраться в течение недели": "hafta ichida hal qilish",
  "Раньше": "Avval",
  "Распаковывает": "Ochadi",
  "Распродажа / акция": "Aksiya-sotuv / aksiya",
  "Рассмотрение": "Ko'rib chiqish",
  "Рассмотрите переход на предоплату или сокращение лимита кредита.": "Oldindan to'lovga o'tish yoki kredit limitini qisqartirishni ko'rib chiqing.",
  "Растёт ли моя выручка по сравнению с прошлым периодом?": "Tushumim o'tgan davrga nisbatan o'smoqdami?",
  "Расход": "Xarajat",
  "Расход (день)": "Chiqim (kun)",
  "Расход (период)": "Chiqim (davr)",
  "Расход (сум)": "Xarajat (so'm)",
  "Расход денег": "Pul chiqimi",
  "Расходы": "Chiqimlar",
  "Расходы на каналы (для ROI)": "Kanallarga xarajatlar (ROI uchun)",
  "Расхождения": "Tafovutlar",
  "Расчёт строится на ваших реальных продажах за последний месяц": "Hisob-kitob oxirgi oydagi haqiqiy sotuvlaringizga asoslanadi",
  "Расширение в регионы": "Hududlarga kengayish",
  "Реактивация спящих": "Uxlayotganlarni qayta faollashtirish",
  "Реактивация через 60 дн": "60 kundan keyin reaktivatsiya",
  "Реактивировать «Алишер К.»": "«Alisher K.» ni qayta faollashtirish",
  "Реальные продажи за сегодня · режим наблюдения": "Bugungi haqiqiy sotuvlar · kuzatuv rejimi",
  "Реальный статус подключений · без макетов": "Ulanishlarning haqiqiy holati · maketlarsiz",
  "Регулярная оплата в срок = скидки + лучшие условия отсрочки в будущем.": "Muntazam o'z vaqtida to'lash = chegirmalar + kelajakda yaxshiroq muddatli shartlar.",
  "Регулярные покупки в последние 60д": "Oxirgi 60 kunda muntazam xaridlar",
  "Редактирование": "Tahrirlash",
  "Редактирование портрета": "Portretni tahrirlash",
  "Редактировать": "Tahrirlash",
  "Редактировать товар": "Tovarni tahrirlash",
  "Результат": "Natija",
  "Реклама Telegram": "Telegram reklamasi",
  "Рекомендации сегодня": "Bugungi tavsiyalar",
  "Рекомендация": "Tavsiya",
  "Рекомендует": "Tavsiya qiladi",
  "Реф. программа": "Ref. dastur",
  "реферал → клиент": "referal → mijoz",
  "Реферальная программа": "Referal dasturi",
  "Решение": "Yechim",
  "Решить →": "Hal qilish →",
  "розница": "chakana",
  "Розничный магазин": "Chakana do'kon",
  "Роли · права · доступы · реальные данные": "Rollar · huquqlar · ruxsatlar · haqiqiy ma'lumotlar",
  "Роли · филиалы · доступ": "Rollar · filiallar · kirish",
  "Роли × Права (правила системы)": "Rollar × Huquqlar (tizim qoidalari)",
  "Роль": "Rol",
  "роспись": "naqsh",
  "рулон": "rulon",
  "ручной работы": "qo'l mehnati",
  "С атрибутами": "Atributli",
  "С болями": "Og'riqlar bilan",
  "С чего начнём?": "Nimadan boshlaymiz?",
  "С JTBD": "JTBD bilan",
  "Сайт": "Sayt",
  "Сайт / SEO": "Sayt / SEO",
  "Сайт менее удобный": "Sayt qulayligi pastroq",
  "Сальдо": "Saldo",
  "Сам товар": "Tovarning o'zi",
  "Самарканд + Бухара + Фергана": "Samarqand + Buxoro + Farg'ona",
  "Самая частая": "Eng ko'p uchraydigan",
  "Сами продажи кассиры и продавцы проводят в своём приложении (POS на телефоне).": "Sotuvlarni kassirlar va sotuvchilar o'z ilovasida amalga oshiradi (telefondagi POS).",
  "Самый частый": "Eng ko'p uchraydigan",
  "Сарафан": "Og'zaki tarqalish",
  "Сборка · разборка · спецификация (BOM)": "Yig'ish · qismlarga ajratish · spetsifikatsiya (BOM)",
  "Свадебный набор": "To'y to'plami",
  "Свадьбы начинаются": "To'ylar boshlanadi",
  "Сверка фактических остатков vs учёт": "Haqiqiy qoldiqlarni hisob bilan solishtirish",
  "сделка": "bitim",
  "Сделка": "Bitim",
  "Сделка возвращена назад": "Bitim orqaga qaytarildi",
  "Сделка продвинута": "Bitim oldinga surildi",
  "сделки": "bitim",
  "сделок": "bitim",
  "Сделок": "Bitimlar",
  "Себестоимость": "Tannarx",
  "Сегмент": "Segment",
  "сегодня": "bugun",
  "Сегодня": "Bugun",
  "Сегодня приходов": "Bugungi kirimlar",
  "Сегодня продаж ещё не было": "Bugun hali sotuvlar bo'lmagan",
  "Сезонник, который много даёт — прогноз": "Ko'p beradigan mavsumiy tovar — prognoz",
  "Сезонность · этапы · KPI на год": "Mavsumiylik · bosqichlar · yillik KPI",
  "Сезонный календарь": "Mavsumiy kalendar",
  "Сейчас": "Hozir",
  "Сейчас — свободный текст. Структурированные атрибуты добавим позже": "Hozircha — erkin matn. Tuzilmali atributlarni keyinroq qo'shamiz",
  "Сентябрь": "Sentyabr",
  "Сервис · UX": "Servis · UX",
  "Сессии": "Sessiyalar",
  "Синхронизация остатков": "Qoldiqlarni sinxronlash",
  "Сканирование склада...": "Ombor skanerlanmoqda...",
  "Скепсис": "Shubha",
  "Скидка −10%": "Chegirma −10%",
  "Скидка −25%": "Chegirma −25%",
  "Скидка 10% на 1-ю покупку": "1-xaridga 10% chegirma",
  "Склад": "Ombor",
  "складовщик": "omborchi",
  "Складовщик": "Omborchi",
  "Скоро": "Yaqin",
  "Скоро срок": "Muddati yaqin",
  "Скрыть": "Yashirish",
  "Скрыть историю": "Tarixni yashirish",
  "Слить": "Birlashtirish",
  "Сложная форма": "Murakkab forma",
  "см": "sm",
  "Смен ролей": "Rol almashinuvlari",
  "Сменили цены": "Narxlarni o'zgartirdi",
  "Смены ролей и AI-запросы логируются": "Rol almashinuvlari va AI-so'rovlar qayd etiladi",
  "Сначала вставьте токен бота": "Avval bot tokenini joylang",
  "Снижение цены может добавить ~": "Narxni pasaytirish ~ qo'shishi mumkin",
  "Снимок текущих остатков → сверка через сканер штрих-кода": "Joriy qoldiqlar surati → shtrix-kod skaneri orqali solishtirish",
  "Совпало": "Mos keldi",
  "Создан приход на склад": "Omborga kirim yaratildi",
  "Создать": "Yaratish",
  "Создать КП за 3 шага": "3 qadamda tijoriy taklif yaratish",
  "Создать списание": "Hisobdan chiqarishni yaratish",
  "Создать PO": "PO yaratish",
  "сообщений": "xabar",
  "сорт (А/Б/В)": "sort (A/B/V)",
  "Состав": "Tarkib",
  "Сосчитано": "Sanaldi",
  "Сотрудник": "Xodim",
  "Сотрудники компании · реальная активность": "Kompaniya xodimlari · haqiqiy faollik",
  "сотрудников": "xodim",
  "Сотрудников нет": "Xodimlar yo'q",
  "Сохранить": "Saqlash",
  "Список": "Ro'yxat",
  "спит": "uxlayapti",
  "Способ": "Usul",
  "Способ оплаты": "To'lov usuli",
  "Спрос +28%, конкуренты дороже на 18%. Прогноз: +4.2M маржи/мес.": "Talab +28%, raqobatchilar 18% qimmat. Prognoz: +4.2M marja/oy.",
  "Спроси у бизнеса": "Biznesdan so'rang",
  "Спроси что-нибудь...": "Biror narsa so'rang...",
  "Спросить": "So'rash",
  "Спящие": "Uxlayotgan",
  "Спящий клиент → реактивация": "Uxlayotgan mijoz → reaktivatsiya",
  "Спящих": "Uxlayotgan",
  "Сравнение цен": "Narxlarni solishtirish",
  "среднее": "o'rtacha",
  "Среднее время": "O'rtacha vaqt",
  "средние": "o'rtacha",
  "Средний чек": "O'rtacha chek",
  "Средний CPL": "O'rtacha CPL",
  "Средний LTV": "O'rtacha LTV",
  "Средняя": "O'rtacha",
  "Средняя (обычная розница)": "O'rtacha (oddiy chakana)",
  "средняя маржа": "o'rtacha marja",
  "Средняя маржа": "O'rtacha marja",
  "Срок": "Muddat",
  "СРОЧНО · ВАЖНО": "SHOSHILINCH · MUHIM",
  "СРОЧНО · НЕВАЖНО": "SHOSHILINCH · MUHIM EMAS",
  "Срочно закупить: Брус 50×100 (250 м³), Шахматы 40×40 (50 шт), Бейсболка синяя (80 шт). Прогноз бюджета: 124M UZS.": "Zudlik bilan xarid qiling: Brus 50×100 (250 m³), Shaxmat 40×40 (50 dona), Ko'k beysbolka (80 dona). Byudjet prognozi: 124M UZS.",
  "Стабильный лидер с колебаниями — буфер 20%": "Tebranishli barqaror lider — 20% bufer",
  "Стабильный середняк — оптимизировать запас": "Barqaror o'rtacha tovar — zaxirani optimallash",
  "Стабильный хвост — минимальный запас": "Barqaror quyruq — minimal zaxira",
  "Стадия": "Bosqich",
  "Стаж": "Tajriba",
  "Статус": "Holat",
  "Статус:": "Holat:",
  "Статья": "Maqola",
  "стиль": "uslub",
  "Стоимость": "Qiymati",
  "Страна": "Davlat",
  "Стратегических целей": "Strategik maqsadlar",
  "сум": "so'm",
  "сум · в кассу": "so'm · kassaga",
  "сум · введено": "so'm · kiritildi",
  "сум · всё время": "so'm · butun davr",
  "сум · вся команда": "so'm · butun jamoa",
  "сум · за период": "so'm · davr uchun",
  "сум · из кассы": "so'm · kassadan",
  "сум · на клиента": "so'm · mijozga",
  "сум · после расходов": "so'm · chiqimlardan keyin",
  "сум выручки": "so'm tushum",
  "сум уже покрыты.": "so'm allaqachon qoplangan.",
  "сум.": "so'm.",
  "сум/день)": "so'm/kun)",
  "Сумма": "Summa",
  "Сумма (UZS)": "Summa (UZS)",
  "Сумма за период": "Davr uchun summa",
  "Сумма закупа": "Xarid summasi",
  "Сформировать КП": "Tijoriy taklif shakllantirish",
  "Сходство": "O'xshashlik",
  "Сценарии": "Stsenariylar",
  "Сценарии «Если → То» · согласования": "«Agar → Unda» stsenariylari · kelishuvlar",
  "Сценарии запаса, найма и рекламы требуют дополнительных данных — появятся в следующих обновлениях.": "Zaxira, yollash va reklama stsenariylari qo'shimcha ma'lumot talab qiladi — keyingi yangilanishlarda paydo bo'ladi.",
  "Сценарий: изменить цены на X%": "Stsenariy: narxlarni X% ga o'zgartirish",
  "Сэкономлено": "Tejaldi",
  "Тег": "Teg",
  "Тег:": "Teg:",
  "Текущая маржа": "Joriy marja",
  "Текущее состояние": "Joriy holat",
  "Текущие запасы · адресное хранение": "Joriy zaxiralar · manzilli saqlash",
  "Телефон": "Telefon",
  "Телефон:": "Telefon:",
  "Темп роста": "O'sish sur'ati",
  "Тест": "Test",
  "Тип": "Tur",
  "Тип добавлен": "Tur qo'shildi",
  "Тип продажи": "Sotuv turi",
  "Тип создан": "Tur yaratildi",
  "Тип удалён": "Tur o'chirildi",
  "Тип:": "Tur:",
  "Типы товаров": "Tovar turlari",
  "Типы, бренды, единицы и атрибуты — всё в одном окне": "Turlar, brendlar, birliklar va atributlar — barchasi bitta oynada",
  "Товар": "Tovar",
  "товарах — нельзя удалить": "tovarda — o'chirib bo'lmaydi",
  "товаров": "tovar",
  "Товаров": "Tovarlar",
  "Товары": "Tovarlar",
  "ток.": "tok.",
  "Токен бота": "Bot tokeni",
  "Только учредитель и ген. директор — менеджерам и кассирам закрыт": "Faqat muassis va bosh direktor — menejerlar va kassirlar uchun yopiq",
  "Топ — кому мы должны": "Top — kimga qarzdormiz",
  "Топ возражений и готовые ответы": "Top e'tirozlar va tayyor javoblar",
  "топ выручки": "tushum bo'yicha top",
  "Топ должников": "Top qarzdorlar",
  "Топ клиентов по LTV": "LTV bo'yicha top mijozlar",
  "Топ товаров": "Top tovarlar",
  "Топ-5 худших по продажам за месяц: Косметика партия 2, Шахматы 50×50, Латун ваза 30см, Чапан XXL, Тарелка 28см. Рекомендую скидку 25% на ликвидацию.": "Oy bo'yicha eng yomon sotilgan top-5: Kosmetika 2-partiya, Shaxmat 50×50, Latun vaza 30sm, Chopon XXL, Likobcha 28sm. Likvidatsiya uchun 25% chegirma tavsiya qilaman.",
  "Топ-бренд": "Top brend",
  "Топ-товары по выручке · точка заказа · мёртвый товар (90 дн)": "Tushum bo'yicha top tovarlar · buyurtma nuqtasi · o'lik tovar (90 kun)",
  "Точка безубыточности": "Zararsizlik nuqtasi",
  "Точка безубыточности = Постоянные расходы ÷ Маржинальность": "Zararsizlik nuqtasi = Doimiy chiqimlar ÷ Marjinallik",
  "Точка касания": "Kontakt nuqtasi",
  "Точку безубыточности не на чём рассчитать. Появятся продажи — расчёт заработает.": "Zararsizlik nuqtasini hisoblash uchun asos yo'q. Sotuvlar paydo bo'lsa — hisoblash ishlaydi.",
  "требуют действий": "amal talab qiladi",
  "требуют действия сейчас": "hozir harakat talab qiladi",
  "Триггер": "Trigger",
  "Триггерим здоровье семьи, безопасность": "Oila salomatligi, xavfsizlikni triggerlaymiz",
  "Триггерим уважение, статус, отношения": "Hurmat, status, munosabatlarni triggerlaymiz",
  "Триггерим экономию или зарабатывание денег": "Tejash yoki pul ishlashni triggerlaymiz",
  "Туристический": "Turistik to'plam",
  "Туристический сезон": "Turistik mavsum",
  "Уведомления и отчёты в Telegram": "Telegramda bildirishnomalar va hisobotlar",
  "Углубление в ответ. «Почему именно качество?»": "Javobni chuqurlashtirish. «Nega aynan sifat?»",
  "удалён": "o'chirildi",
  "Удалить": "O'chirish",
  "Удалить запись": "Yozuvni o'chirish",
  "Удалить портрет": "Portretni o'chirish",
  "Удалить тип": "Turni o'chirish",
  "Удалить чат": "Chatni o'chirish",
  "Удалить этот чат?": "Bu chatni o'chirilsinmi?",
  "Узбекская эстетика — туристы": "O'zbek estetikasi — turistlar",
  "Узбекский сувенир BASE": "O'zbek suvenir BASE",
  "Узнавание": "Tanishuv",
  "Умеренный · средняя предсказуемость": "O'rtacha · o'rtacha bashoratlilik",
  "упадёт": "tushadi",
  "упак": "qadoq",
  "Упаковка": "Qadoqlash",
  "Управление наличными": "Naqd pul boshqaruvi",
  "Уровни · кэшбек · реферальная программа": "Darajalar · keshbek · referal dasturi",
  "Усилить Instagram": "Instagram-ni kuchaytirish",
  "Условия уровней": "Darajalar shartlari",
  "успешно завершена": "muvaffaqiyatli yakunlandi",
  "Уточнение по доставке · 6 мин": "Yetkazish bo'yicha aniqlik · 6 daq",
  "Участников": "Ishtirokchilar",
  "учатся": "o'qiyapti",
  "учредитель": "muassis",
  "Учредитель": "Muassis",
  "ушёл": "ketdi",
  "Ушли": "Ketgan",
  "Факт": "Fakt",
  "Фев": "Fev",
  "Февраль": "Fevral",
  "Филиал": "Filial",
  "Филиалов": "Filiallar",
  "Филиалы": "Filiallar",
  "Филиалы · валюты · языки · реальные данные": "Filiallar · valyutalar · tillar · haqiqiy ma'lumotlar",
  "Финансовая грамотность": "Moliyaviy savodxonlik",
  "Финансы": "Moliya",
  "Форма добавления — клик ✕ в карточке клиента → «Создать на основе»": "Qo'shish shakli — mijoz kartasida ✕ bosing → «Asosida yaratish»",
  "Формат": "Format",
  "Фото": "Foto",
  "хвост": "quyruq",
  "Холодные звонки": "Sovuq qo'ng'iroqlar",
  "Холодный звонок": "Sovuq qo'ng'iroq",
  "Хранятся как bcrypt-хеши — исходный пароль восстановить нельзя": "bcrypt-xesh sifatida saqlanadi — dastlabki parolni tiklab bo'lmaydi",
  "ЦА-аватаров": "auditoriya avatarlari",
  "цвет": "rang",
  "цвет / размер / прочее": "rang / o'lcham / boshqa",
  "Цена": "Narx",
  "Цена · скидка · маржа — прогноз на ваших реальных данных": "Narx · chegirma · marja — sizning haqiqiy ma'lumotlaringiz bo'yicha prognoz",
  "Цена закупки": "Xarid narxi",
  "Цена закупки (UZS)": "Xarid narxi (UZS)",
  "Цена продажи (UZS)": "Sotuv narxi (UZS)",
  "Ценность клиента · повторные покупки · сегменты · реальные данные": "Mijoz qiymati · takroriy xaridlar · segmentlar · haqiqiy ma'lumotlar",
  "Цены ниже ЦБ": "Markaziy bankdan past narxlar",
  "Цифры ниже — настоящие, обновляются по мере продаж.": "Quyidagi raqamlar haqiqiy, sotuvlar bo'yicha yangilanib boradi.",
  "Часов контента": "Kontent soatlari",
  "Чат · анализ финансов · рекомендации": "Chat · moliya tahlili · tavsiyalar",
  "Чат с менеджером": "Menejer bilan chat",
  "Чаты не найдены. Откройте бота в Telegram, нажмите «Старт», затем повторите.": "Chatlar topilmadi. Telegramda botni oching, «Start» bosing, keyin qayta urinib ko'ring.",
  "Чаты хранятся локально в браузере": "Chatlar brauzerda lokal saqlanadi",
  "Чек с QR обратной связи": "QR fikr-mulohaza bilan chek",
  "Чеков сегодня": "Bugun cheklar",
  "Чистая прибыль": "Sof foyda",
  "Чистая прибыль месяца:": "Oylik sof foyda:",
  "Что делать": "Nima qilish kerak",
  "Что ещё я могу улучшить?": "Yana nimani yaxshilashim mumkin?",
  "Что именно вас останавливает? Давайте разберём прямо сейчас.": "Aynan nima sizni to'xtatyapti? Keling, hozir tahlil qilamiz.",
  "Что мы должны · приоритет по сроку": "Biz nima qarzdormiz · muddat bo'yicha ustuvorlik",
  "Что писать в Reels на этой неделе, чтобы привлечь клиентов?": "Mijozlarni jalb qilish uchun bu hafta Reels'ga nima yozish kerak?",
  "Что писать в Reels на этой неделе?": "Bu hafta Reels'ga nima yozish kerak?",
  "Что плохо продаётся?": "Nima yomon sotilyapti?",
  "Что у меня горит сегодня — что разобрать в первую очередь?": "Bugun nima yonmoqda — birinchi navbatda nimani ko'rib chiqish kerak?",
  "Что-Где-Почему · симуляторы · рекомендации": "Nima-Qayer-Nega · simulyatorlar · tavsiyalar",
  "Чтобы видеть какой канал приносит деньги — указывайте «Откуда пришёл клиент» при создании клиента (раздел «Клиенты»). Как появятся источники — здесь будет ROI каждого канала.": "Qaysi kanal pul keltirayotganini ko'rish uchun — mijoz yaratishda «Mijoz qayerdan keldi»ni ko'rsating («Mijozlar» bo'limi). Manbalar paydo bo'lgach — bu yerda har bir kanalning ROI ko'rsatiladi.",
  "Чтобы выйти в ноль, нужно ещё продать на": "Nolga chiqish uchun yana shuncha sotish kerak",
  "Чувствительность к цене": "Narxga sezgirlik",
  "Чувствительность к цене:": "Narxga sezgirlik:",
  "Шахматы 40×40": "Shaxmat 40×40",
  "Школа · корп. подарки": "Maktab · korp. sovg'alar",
  "шт": "dona",
  "Штрих-код": "Shtrix-kod",
  "Штучные": "Donali",
  "Экономия от AI": "AI tejamkorligi",
  "Экспорт": "Eksport",
  "Эмоция": "Emotsiya",
  "Этап": "Bosqich",
  "Эти правила применяются сервером на каждом запросе (auth-middleware) — обойти их из браузера нельзя.": "Bu qoidalar har bir so'rovda server tomonidan qo'llaniladi (auth-middleware) — ularni brauzerdan chetlab o'tib bo'lmaydi.",
  "Это": "Bu",
  "Это образец интерфейса для согласования. Реальные данные подключим в следующих обновлениях. Кнопки в макете не сохраняют ничего.": "Bu kelishish uchun interfeys namunasi. Haqiqiy ma'lumotlarni keyingi yangilanishlarda ulaymiz. Maketdagi tugmalar hech narsani saqlamaydi.",
  "Это трендовая проекция по фактическим данным, а не гарантия. Резкие изменения продаж/расходов её меняют.": "Bu haqiqiy ma'lumotlar bo'yicha trend proyeksiyasi, kafolat emas. Sotuv/chiqimning keskin o'zgarishi uni o'zgartiradi.",
  "Эфир": "Efir",
  "Эффективность каналов": "Kanallar samaradorligi",
  "Эффективность продавцов": "Sotuvchilar samaradorligi",
  "Я понимаю. А когда у вас будет 10 минут — на этой неделе или в среду?": "Tushunaman. Sizda qachon 10 daqiqa bo'ladi — shu hafta yoki chorshanba kuni?",
  "Языков": "Tillar",
  "Янв": "Yan",
  "Январь": "Yanvar",
  "ящик": "yashik",
  "ABC-анализ": "ABC-tahlil",
  "AI": "AI",
  "AI анализирует ваши реальные цифры…": "AI sizning real raqamlaringizni tahlil qilmoqda…",
  "AI думает...": "AI o'ylayapti...",
  "AI может ошибаться — всегда проверяй важные цифры в самой системе. История хранится локально.": "AI xato qilishi mumkin — muhim raqamlarni har doim tizimning o'zida tekshiring. Tarix lokal saqlanadi.",
  "AI-анализ": "AI-tahlil",
  "AI-анализ этих данных": "Bu ma'lumotlarning AI-tahlili",
  "AI-доступ": "AI-ruxsat",
  "AI-запросов": "AI-so'rovlar",
  "AI-консультант": "AI-maslahatchi",
  "AI-консультант (DeepSeek)": "AI-maslahatchi (DeepSeek)",
  "AI-токенов": "AI-tokenlar",
  "AIDA / PAS / 4U · покажи проблему → агитация → решение": "AIDA / PAS / 4U · muammoni ko'rsat → targ'ibot → yechim",
  "B2B / корпоративные": "B2B / korporativ",
  "B2B доля": "B2B ulushi",
  "B2B спецпредложение": "B2B maxsus taklif",
  "B2C розничный покупатель": "B2C chakana xaridor",
  "BOFU · Продажа": "BOFU · Sotuv",
  "Cash cow — держать запас, частые поставки": "Cash cow — zaxirani saqlash, tez-tez yetkazib berish",
  "Cash Flow (7 дней)": "Cash Flow (7 kun)",
  "Click": "Click",
  "Cold call · ODC · возражения · Pul-Sog'liq-Munosabat": "Cold call · ODC · e'tirozlar · Pul-Sog'liq-Munosabat",
  "Cold calls и возражения": "Cold calls va e'tirozlar",
  "CRM · работа с историей": "CRM · tarix bilan ishlash",
  "Customer Journey Map": "Customer Journey Map",
  "Email отправлен": "Email yuborildi",
  "Email-серия": "Email-seriya",
  "Eng/Ru сайт": "Eng/Ru sayt",
  "Excel сгенерирован": "Excel yaratildi",
  "Hook (5 сек)": "Hook (5 sek)",
  "HR": "HR",
  "https://instagram.com/... или идея-референс": "https://instagram.com/... yoki referens-g'oya",
  "ℹ️ Активность = продажи, проведённые сотрудником. Управление ролями и доступами — в разделе «Сотрудники».": "ℹ️ Faollik = xodim tomonidan amalga oshirilgan sotuvlar. Rollar va ruxsatlarni boshqarish — «Xodimlar» bo'limida.",
  "ℹ️ Полоса — % от результата лидера. Цифры обновляются с каждой продажей: готовый ежемесячный конкурс для команды. Детальные KPI — в разделе «KPI команды».": "ℹ️ Chiziq — lider natijasidan %. Raqamlar har bir sotuv bilan yangilanadi: jamoa uchun tayyor oylik tanlov. Batafsil KPI — «Jamoa KPI» bo'limida.",
  "ℹ️ Статус «Активна» означает, что интеграция реально работает на сервере прямо сейчас — здесь нет демонстрационных переключателей.": "ℹ️ «Faol» holati integratsiya hozir serverda haqiqatan ishlayotganini bildiradi — bu yerda namoyish uchun o'zgartirgichlar yo'q.",
  "ℹ️ LTV = сумма всех покупок клиента за всё время. Удержать существующего клиента дешевле, чем привлечь нового — растите повторные покупки через лояльность и сервис.": "ℹ️ LTV = mijozning butun davr mobaynidagi barcha xaridlari yig'indisi. Mavjud mijozni ushlab qolish yangisini jalb qilishdan arzonroq — sodiqlik va xizmat orqali takroriy xaridlarni oshiring.",
  "ℹ️ Telegram подключается вами самостоятельно за пару минут. Платёжные и маркетплейс-интеграции требуют договора/кабинета у провайдера — напишите нам, подключим.": "ℹ️ Telegramni o'zingiz bir necha daqiqada ulaysiz. To'lov va marketpleys integratsiyalari provayderda shartnoma/kabinet talab qiladi — bizga yozing, ulaymiz.",
  "Instagram реклама": "Instagram reklama",
  "Instagram, Telegram, сарафан": "Instagram, Telegram, og'zaki tarqalish",
  "JTBD": "JTBD",
  "JTBD — что покупает": "JTBD — nima sotib oladi",
  "JWT-токены с автоистечением через 24 часа": "24 soatdan keyin avtomatik tugaydigan JWT-tokenlar",
  "KZ + RU исследовать": "KZ + RU o'rganish",
  "Live": "Live",
  "Live · CRUD": "Live · CRUD",
  "Live-карта": "Jonli xarita",
  "LTV ≥ 5M UZS · активные": "LTV ≥ 5M UZS · faol",
  "LTV 3.4M, не покупал 60 дн.": "LTV 3.4M, 60 kundan beri xarid qilmagan.",
  "LTV по сегментам": "Segmentlar bo'yicha LTV",
  "LTV считается по клиентам из базы. Привязывайте продажи к клиентам в кассе — и здесь появится ценность каждого.": "LTV bazadagi mijozlar bo'yicha hisoblanadi. Sotuvlarni kassada mijozlarga bog'lang — va bu yerda har birining qiymati paydo bo'ladi.",
  "MOFU · Вовлечение": "MOFU · Jalb etish",
  "Munosabat (Отношения)": "Munosabat (Munosabatlar)",
  "NPS · реф. программа": "NPS · ref. dastur",
  "NPS < 7 → Звонок": "NPS < 7 → Qo'ng'iroq",
  "NPS-опрос через 7 дней": "7 kundan keyin NPS so'rovi",
  "ODC техника": "ODC texnikasi",
  "OZON / Wildberries": "OZON / Wildberries",
  "P&L · Май 2026": "P&L · May 2026",
  "P&L по месяцам": "Oylar bo'yicha P&L",
  "P&L по месяцам + прогноз на 3 месяца · реальные данные": "Oylar bo'yicha P&L + 3 oylik prognoz · haqiqiy ma'lumotlar",
  "Payme": "Payme",
  "PDF отправлен на": "PDF yuborildi:",
  "Pul (Деньги)": "Pul (Pul)",
  "R · касса": "R · kassa",
  "R · подтверждение": "R · tasdiqlash",
  "R · свой филиал": "R · o'z filiali",
  "RFM-разбивка — кому звонить, кого возвращать": "RFM-taqsimot — kimga qo'ng'iroq qilish, kimni qaytarish",
  "ROI = выручка с канала ÷ расход на него. CAC = расход ÷ кол-во покупателей. Чтобы посчитать ROI — внесите расходы ниже.": "ROI = kanaldan tushum ÷ unga xarajat. CAC = xarajat ÷ xaridorlar soni. ROI ni hisoblash uchun — quyida xarajatlarni kiriting.",
  "ROI всего": "Jami ROI",
  "ROI по каналам · CPL · поток лидов": "Kanallar bo'yicha ROI · CPL · lidlar oqimi",
  "RW · только свои": "RW · faqat o'ziniki",
  "SEO органика": "SEO organik",
  "SMS «спасибо»": "SMS «rahmat»",
  "SMS UZ (Eskiz.uz)": "SMS UZ (Eskiz.uz)",
  "SMS-рассылка со скидкой 10% · напомните о себе · вернуть на радар": "10% chegirma bilan SMS-tarqatish · o'zingizni eslating · radarga qaytaring",
  "SMS-уведомления клиентам": "Mijozlarga SMS-bildirishnomalar",
  "Sog'liq (Здоровье)": "Sog'liq (Salomatlik)",
  "Telegram канал": "Telegram kanal",
  "Telegram Bot": "Telegram Bot",
  "Telegram: топ-3": "Telegram: top-3",
  "TOFU · Привлечение": "TOFU · Jalb qilish",
  "UZS · выручка": "UZS · tushum",
  "UZS · по закупке": "UZS · xarid bo'yicha",
  "VIP": "VIP",
  "vs 3-5 дней у конкурентов": "raqobatchilarda 3-5 kunga nisbatan",
  "vs позиций": "pozitsiyalarga nisbatan",
  "X — стабильный спрос": "X — barqaror talab",
  "Y — средние колебания": "Y — o'rtacha tebranishlar",
  "Z — нестабильный": "Z — beqaror"
};
